### PR TITLE
Convert kmeans.js to a .tsx file

### LINKED ISSUE #81: Convert kmeans.js to TypeScript
Reference other module TypeScript implementations - simply adding types to the code and a ticket to clean up the code for this demo.

### PR DESCRIPTION
**Pull request by jakeisnt**
Closes #81

### CODE REVIEW

**Comment by jakeisnt** [comment]
#81

**Comment by jakeisnt** [comment]
Note that a lot of the variable names in this file are far from perfect. We felt that changing all of the names would take considerably more effort than it might be worth and that this refactoring so far has made the modules much more usable externally.

If we should go through and spend time renaming everything, just let us know :+1:

**Review by maxpinheiro — CHANGES_REQUESTED** [review]
All of the changes you made, both with typescript conversion & general cleanup, look great - awesome job. My one concern is that there's a whole lot going on in the same file. Kmeans has 4 components and several helper functions, which makes the file pretty confusing to navigate. I think we could benefit from moving the KMeansStepExample and InteractiveClusteringExample components into their own files.

**Comment by jakeisnt** [comment]
Created files for each of the modules! This should be good to go now.

**Review by maxpinheiro — APPROVED** [review]
Looks great! You're good to go

**Comment by jakeisnt** [comment]
Worth noting that this breaks the drag and drop functionality for one of the kmeans modules. We'll wait until the PR branched off of this one has a fix to merge both of them.

**Comment by jakeisnt** [comment]
Going to close this because the fix was split between this branch and one for a subsequent ticket. We can merge that one instead.

**Pull request closed without merging**
